### ISSUE TITLE
Example temperature.yaml fails to execute

### ISSUE THREAD

**Issue by mxklb** [asyncapi/python-paho-template#10]
#### Syntax Error in Example
Generated code snippets `main.py` fails = is not executable

```
python3 main.py 
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from sensorReading import SensorReading
  File "/home/xam/Develop/docker/test/asyncapi/asyncapi-to-python/output/sensorReading.py", line 5
    from &lt;anonymous-schema-3&gt; import &lt;anonymous-schema-3&gt;
         ^
SyntaxError: invalid syntax
```

The generated `sensorReading,py` contains invalid syntax.

#### How to Reproduce
I put everything into a docker container, so reproducing is just generating python pub/sub code from your *samples/temperature.yaml*, therefore try https://github.com/mxklb/asyncapi-to-python

Afterwards execute `python3 main.py` in the output folder.

#### Expected behavior
Generate code is executable.

**Comment by damaru-inc** [comment]
Sorry I missed this one, I'll look at it over the next few days.

**Comment by mxklb** [comment]
I just tested it again and the bug is still alive, wrong syntax in `sensorReading,py` import statement.

Actually I didn't use async api for my python projects because it does not looks stable to me at this point .. but I'm looking forward to move my python projects to an API first development workflow, where async API still looks like the right tool to me. 

I'm looking forward to see improvements in the python code generator, thank you so far..

**Comment by damaru-inc** [comment]
This is a duplicate if issue #4 and has been fixed in https://github.com/asyncapi/python-paho-template/pull/13.

**Comment by mxklb** [comment]
do you plan to make a new release containing your fixes? In the actual release this bug is still allive ..

**Comment by derberg** [comment]
@damaru-inc hey, you did not use conventional commits in PR and new version was not released. Please make some empty PR or a Pr with some minor change with `fix: ` prefix

**Comment by mxklb** [comment]
You Code is still not working with the new version 0.2.5. Maybe you should reopen this .. 

The above `SyntaxError: invalid syntax` is fixed, but your SensorReadings example still fails directly:

Have you tested it?

```
python3 main.py 
INFO:root:Start of main.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 33, in main
    sensorTemperatureFahrenheitMessenger = messaging.Messaging(config, 'sensor/temperature/fahrenheit', sensorTemperatureFahrenheit)
  File "/home/xam/Develop/docker/asyncapi/asyncapi-to-python/output/messaging.py", line 14, in __init__
    logging.info("Default host:", defaultHost)
Message: 'Default host:'
Arguments: ('None',)
Host:  ubuntu port:  1883
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 37, in main
    payload = SensorReading()
TypeError: __init__() missing 3 required positional arguments: 'sensorId', 'temperature', and 'baseUnit'
```
Maybe python is not your/my primary language but if you pretend to support it, I expect at least your hello world example to work.

I still can't use it and I would still not recommend to use asyncapi for python projects. When do you plan to support python code generation - at least for your own examples? What happens if I apply more complex async API as your sensorReading? Sorry but this isn't tested well, closing issues but not testing against subsequent failures doesn't look promising at all ..

P.S. To reproduce, simple change .env file in the repo I linked above to use your latest 0.2.5 release -> et voila the above error appears. At least after solving prior default config.ini failure - I had to set a valid a broker URL first, otherwise crashed like ..

```
python3 main.py 
INFO:root:Start of main.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 33, in main
    sensorTemperatureFahrenheitMessenger = messaging.Messaging(config, 'sensor/temperature/fahrenheit', sensorTemperatureFahrenheit)
  File "/home/xam/Develop/docker/asyncapi/asyncapi-to-python/output/messaging.py", line 14, in __init__
    logging.info("Default host:", defaultHost)
Message: 'Default host:'
Arguments: ('None',)
Host:  None port:  1883
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 33, in main
    sensorTemperatureFahrenheitMessenger = messaging.Messaging(config, 'sensor/temperature/fahrenheit', sensorTemperatureFahrenheit)
  File "/home/xam/Develop/docker/asyncapi/asyncapi-to-python/output/messaging.py", line 43, in __init__
    self.client.connect(host, port)
  File "/home/xam/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/home/xam/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known 
```

**Comment by damaru-inc** [comment]
Thanks for reporting this.

As much as I try to do quality work, I do make the occasional mistake! I do test my code before I release it, I'm not sure how this bug got through.

I just fixed it in a new issue #16  and the fix should be available on npm soon. In the mean time, you can just remove the 'logging.info' line in messaging.py, line 14 of the generated code.

**Comment by mxklb** [comment]
Nice, I know it's not possible to keep track of everything, this is 100% human, good to have gh issues :+1: 
And thx for the quick relpy and fix, i'll try again these days when I find time to do so, i'll report here .. looking good!

**Comment by mxklb** [comment]
I'll checked again today, sadly without success ..

When using 0.2.7 there is still one of the bugs (as posted above) in the generated code:
```
INFO:root:Start of main.
Host:  ubuntu port:  1883
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 37, in main
    payload = SensorReading()
TypeError: __init__() missing 3 required positional arguments: 'sensorId', 'temperature', and 'baseUnit' 
```
Clear Error Message: Wrong usage of class SensorReading: `payload = SensorReading()`
To reproduce this a dockerized environment: https://github.com/mxklb/asyncapi-to-python

**Comment by damaru-inc** [comment]
Sorry for the delayed response. The generated code looks like this, lines 36 and 37:

   # Example of how to publish a message. You will have to add arguments to the constructor on the next line:
   payload = SensorReading()

I think the comment makes it clear that it is expected that the user will have to do some editing to make it work. The template is intended to give you something to start with. That being said, it is my intention to add arguments to this sample code at some point.

**Comment by damaru-inc** [comment]
I agree, that's why I've added issue #27 as I noted in my previous comment.
